betterPizza/urls.py
from django.urls import include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^login/', include('login.urls')),
    re_path(r'^forum/', include('forum.urls'))
]

forum/urls.py
from django.urls import re_path
from . import views

app_name = 'forum'
urlpatterns = [\
    re_path(r'^$', views.forum, name='index'),
    re_path(r'^logout', views.logout, name='logout'),
    re_path(r'^', views.forum, name='all-else'), # catches all other queries and sends it to the forum view
]

login/urls.py
from django.urls import re_path, reverse
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    re_path(r'^$', LoginView.as_view(
        template_name='login/index.html'
    ), name='login'),
    re_path(r'^logout', views.logout, name='logout'),
]

forum/models.py
from django.db import models

# Create your models here.

forum/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout_then_login

# Create your views here.
@login_required
def forum(request):
    return render(request, 'forum/forum.html')

def logout(request):
    return logout_then_login(request)

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


# Create your views here.
def logout(request):
    return logout_then_login(request, login_url='login')

forum/templates/forum/forum.html
<!DOCTYPE html>
{% load render_bundle from webpack_loader %}

<h2>Logged in as {{ user.username }}</h2>

<div id="app"></div>

<form action="{% url 'forum:logout' %}">
    <button>logout</button>
</form>

{% render_bundle 'main' %}

login/templates/login/index.html
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css" integrity="sha256-HxaKz5E/eBbvhGMNwhWRPrAR9i/lG1JeT4mD6hCQ7s4=" crossorigin="anonymous" />
<link rel="stylesheet" type="text/css" href="{% static 'login/set2.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'login/login.css' %}" />

<form method="post" action="{% url 'login' %}">
    {% csrf_token %}

    <span class="input input--chisato">
        <input type="text" name="username" id="user" class="input__field input__field--chisato" required autofocus />
        <label for="user" class="input__label input__label--chisato">
            <span class="input__label-content input__label-content--chisato" data-content="username">username</span>
        </label>
    </span>

    <span class="input input--chisato">
        <input type="password" id="pass" name="password" class="input__field input__field--chisato" required />
        <label for="pass" class="input__label input__label--chisato">
            <span class="input__label-content input__label-content--chisato" data-content="pass">pass</label>
        </label>
    </span>

    <input type="submit" value="login" id="submit" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

<script src="{% static 'login/input.js' %}"></script>